composer:
  email: composer@email.com
  github: composer
  library: library
  name: A Composer
  website: www.composer.com
server_options:
  audio_bus_channel_count: 128
  block_size: 64
  buffer_count: 1024
  control_bus_channel_count: 4096
  hardware_buffer_size: null
  initial_node_id: 1000
  input_bus_channel_count: 8
  input_device: null
  input_stream_mask: false
  load_synthdefs: true
  maximum_node_count: 1024
  maximum_synthdef_count: 1024
  memory_locking: false
  memory_size: 8192
  output_bus_channel_count: 8
  output_device: null
  output_stream_mask: false
  protocol: udp
  random_number_generator_count: 64
  remote_control_volume: false
  restricted_path: null
  sample_rate: null
  verbosity: 0
  wire_buffer_count: 64
  zero_configuration: false
title: pipermeth001
